---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: web-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-test
  labels:
    app: web-test
spec:
  selector:
    matchLabels:
      app: web-test
  replicas: 1
  template:
    metadata:
      annotations:
        consul.hashicorp.com/connect-inject: "true"
        consul.hashicorp.com/connect-service-upstreams: "vault:1234"
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "web-test"
        vault.hashicorp.com/agent-inject-secret-database-config.txt: "secret/data/database/config"
        vault.hashicorp.com/service: https://vault.vault.svc:8200
        vault.hashicorp.com/ca-key: /vault/tls/vault-ca.pem
        vault.hashicorp.com/tls-secret: vault-ca
      labels:
        app: web-test
    spec:
      serviceAccountName: web-test
      containers:
        - name: web-test
          image: jweissig/app:0.0.1
