global:
  name: consul
  image: consul:1.8.0-beta1
  datacenter: us-west-2-hashicorp

  # TLS configures whether Consul components use TLS.
  tls:
    # TLS must be enabled for federation in Kubernetes.
    enabled: true
    httpsOnly: true
    verify: true

    #federation:
    #  enabled: true
    #  # This will cause a Kubernetes secret to be created that
    #  # can be imported by secondary datacenters to configure them
    #  # for federation.
    #  createFederationSecret: true

  # ACLS
  acls:
    manageSystemACLs: true
    # If ACLs are enabled, we must create a token for secondary
    # datacenters to replicate ACLs.
    createReplicationToken: true

  # Gossip encryption secures the protocol Consul uses to quickly
  # discover new nodes and detect failure.
  gossipEncryption:
    secretName: consul-gossip-key
    secretKey: key

server:
  replicas: 1
  bootstrapExpect: 1
  storage: 10Gi

client:
  grpc: true

connectInject:
  # Consul Connect service mesh must be enabled for federation.
  enabled: true

syncCatalog:
  enabled: true
  addK8SNamespaceSuffix: false

#Mesh Gateway
#meshGateway:
#  # Mesh gateways are gateways between datacenters. They must be enabled
#  # for federation in Kubernetes since the communication between datacenters
#  # goes through the mesh gateways.
#  replicas: 1
#  enabled: true
#  service:
#    annotations: |
#      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
#      service.beta.kubernetes.io/aws-load-balancer-type: nlb 

#ui:
#  service:
#    type: LoadBalancer
#    annotations: |
#      service.beta.kubernetes.io/aws-load-balancer-internal: "true"
#      service.beta.kubernetes.io/aws-load-balancer-type: elb
