---
# This is the final configuration for vault.  It assumes
# that a TLS certificate was generated and is available.
global:
  tlsDisable: 0
injector:
  authPath: "auth/kube-uswest2-hashicorp"
server:
  annotations: |
    consul.hashicorp.com/connect-inject: "true"
    consul.hashicorp.com/connect-service-port: "8080"
  standalone:
    enabled: true
    config: |
      ui=true
      listener "tcp" {
        address = "0.0.0.0:8200"
        cluster_address = "0.0.0.0:8201"
        #tls_disable = true
        tls_disable = false
        tls_cert_file = "/vault/userconfig/vault-cert/tls.crt"
        tls_key_file  = "/vault/userconfig/vault-cert/tls.key"
        tls_client_ca_file = "/vault/userconfig/vault-cert/ca.crt"
      }

      listener "tcp" {
        tls_disable = true
        address = "127.0.0.1:8080"
      }

      storage "file" {
        path = "/vault/data"
      }

  #These are certificate specific items
  extraEnvironmentVars:
    VAULT_ADDR: http://127.0.0.1:8080

  extraVolumes:
  - type: secret
    name: vault-cert # Matches the ${SECRET_NAME} from above
  #---

  service:
    enabled: true

  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: null
    accessMode: ReadWriteOnce
