---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: vault-issuer
  namespace: cert-manager
spec:
  vault:
    path: pki_vault/sign/vault
    server: http://127.0.0.1:8080
    auth:
      kubernetes:
        role: cert-manager
        mountPath: /v1/auth/kube-uswest2-hashicorp
        secretRef:
          name: <cert-manager-secret>
          key: token
