---
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: vault-cert
  namespace: vault
spec:
  secretName: vault-cert
  duration: 24h
  renewBefore: 4h
  issuerRef:
    kind: ClusterIssuer
    name: vault-issuer
  commonName: vault
  dnsNames:
  - localhost
  - vault 
  - vault.vault
  - vault.vault.svc
  - vault.vault.svc.cluster.local
